name: Inevent Android Pull Request & Master CI

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install gradle
        run: |
          sudo apt-get install gradle
      - name: Decrypt google-services.json
        run: |
          openssl enc -aes-256-cbc -salt -in app/google-services.json.enc -out app/google-services.json -pass pass:${{ secrets.ENC_PASS }} -d
      - name: Unit tests
        run: |
          echo "google.client-id=${{ secrets.GOOGLE_CLIENT_ID }}" >> local.properties
          echo "google.map.key=${{ secrets.GOOGLE_MAP_KEY }}" >> local.properties
          bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install gradle
        run: |
          sudo apt-get install gradle
      - name: Decrypt google-services.json
        run: |
          openssl enc -aes-256-cbc -salt -in app/google-services.json.enc -out app/google-services.json -pass pass:${{ secrets.ENC_PASS }} -d
      - name: Build debug APK
        run: |
          echo "google.client-id=${{ secrets.GOOGLE_CLIENT_ID }}" >> local.properties
          echo "google.map.key=${{ secrets.GOOGLE_MAP_KEY }}" >> local.properties
          bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Inevent App
          path: app/build/outputs/apk/debug/app-debug.apk
